/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
export namespace Components {
    interface MyComponent {
        /**
          * The first name
         */
        "first": string;
        /**
          * The last name
         */
        "last": string;
        /**
          * The middle name
         */
        "middle": string;
    }
    interface WebTrainingPersonal {
    }
}
declare global {
    interface HTMLMyComponentElement extends Components.MyComponent, HTMLStencilElement {
    }
    var HTMLMyComponentElement: {
        prototype: HTMLMyComponentElement;
        new (): HTMLMyComponentElement;
    };
    interface HTMLWebTrainingPersonalElement extends Components.WebTrainingPersonal, HTMLStencilElement {
    }
    var HTMLWebTrainingPersonalElement: {
        prototype: HTMLWebTrainingPersonalElement;
        new (): HTMLWebTrainingPersonalElement;
    };
    interface HTMLElementTagNameMap {
        "my-component": HTMLMyComponentElement;
        "web-training-personal": HTMLWebTrainingPersonalElement;
    }
}
declare namespace LocalJSX {
    interface MyComponent {
        /**
          * The first name
         */
        "first"?: string;
        /**
          * The last name
         */
        "last"?: string;
        /**
          * The middle name
         */
        "middle"?: string;
    }
    interface WebTrainingPersonal {
    }
    interface IntrinsicElements {
        "my-component": MyComponent;
        "web-training-personal": WebTrainingPersonal;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "my-component": LocalJSX.MyComponent & JSXBase.HTMLAttributes<HTMLMyComponentElement>;
            "web-training-personal": LocalJSX.WebTrainingPersonal & JSXBase.HTMLAttributes<HTMLWebTrainingPersonalElement>;
        }
    }
}
